# Generated by Django 3.2.10 on 2023-11-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCommomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1080)),
            ],
        ),
        migrations.CreateModel(
            name='RankingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('money', models.FloatField(default=0)),
                ('email', models.EmailField(default='', max_length=50)),
                ('number_phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('access_token', models.CharField(default='test_<function generate_random_string at 0x0000013A97114C10>', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1080)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_app.usermodel')),
            ],
        ),
    ]
