# Generated by Django 3.2.10 on 2023-11-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='access_token',
            field=models.CharField(default='test_eZvkkJqi0GrkfqG74xOj', max_length=50),
        ),
    ]
