# Generated by Django 3.2.10 on 2023-11-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_usermodel_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='access_token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
