# Generated by Django 3.2.10 on 2023-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_usermodel_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='number_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
