# Generated by Django 3.2.10 on 2023-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_alter_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
