# Generated by Django 3.2.10 on 2023-11-20 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_usermodel_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcommommodel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificationusermodel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_app.usermodel'),
        ),
    ]
