# Generated by Django 3.2.10 on 2023-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_auto_20231120_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(default='media/base-user.png', upload_to=''),
        ),
    ]
