# Generated by Django 3.2.10 on 2023-09-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1500)),
                ('type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_data', models.CharField(max_length=40)),
                ('data', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawMoneyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(default=0, max_length=30)),
                ('stk', models.CharField(max_length=20)),
                ('ttk', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(default=1, max_length=12)),
                ('count_pass', models.IntegerField(default=0)),
                ('money', models.CharField(default=0, max_length=20)),
                ('is_seen_noti', models.BooleanField(default=True)),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='study.notificationsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='study.questionsmodel')),
            ],
        ),
    ]
