# Generated by Django 4.2 on 2023-08-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersmodel',
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionsmodel',
            old_name='questions',
            new_name='question',
        ),
    ]
