# Generated by Django 4.2.4 on 2023-09-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_rename_questions_answersmodel_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_data', models.CharField(max_length=40)),
                ('data', models.CharField(max_length=5000)),
            ],
        ),
    ]
