# Generated by Django 4.2.4 on 2023-09-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_storagedatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersmodel',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='study.questionsmodel'),
        ),
    ]
