# Generated by Django 3.2.10 on 2023-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20230913_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='message',
            field=models.CharField(default=None, max_length=1500),
        ),
    ]
