# Generated by Django 3.2.10 on 2023-09-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_usermodel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='message',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='notification',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.notificationsmodel'),
        ),
    ]
