# Generated by Django 3.2.10 on 2023-09-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20230913_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='user',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
