# Generated by Django 3.2.10 on 2023-09-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_contactmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='massage',
            new_name='message',
        ),
    ]
