# Generated by Django 3.2.10 on 2023-09-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_auto_20230911_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsmodel',
            name='message',
            field=models.CharField(max_length=1500),
        ),
    ]
