# Generated by Django 3.2.10 on 2023-09-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_rename_massage_contactmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmoneymodel',
            name='username',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
