# Generated by Django 3.2.10 on 2023-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_alter_notificationsmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedatamodel',
            name='money',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
