# Generated by Django 3.2.10 on 2023-10-18 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postmodel_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
