# Generated by Django 3.2.10 on 2023-10-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='images/')),
                ('create_at', models.DateField()),
            ],
        ),
    ]
