# Generated by Django 3.2.10 on 2023-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='create_at',
            field=models.DateTimeField(),
        ),
    ]
