# Generated by Django 3.2.10 on 2023-11-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='user_comment',
            new_name='user',
        ),
    ]
