# Generated by Django 3.2.10 on 2023-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_alter_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
