# Generated by Django 3.2.10 on 2023-11-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_postmodel_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
