# Generated by Django 3.2.10 on 2023-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_commentmodel_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
