# Generated by Django 3.2.10 on 2023-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_alter_postmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
