# Generated by Django 3.2.10 on 2023-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_alter_postmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='user',
            field=models.CharField(max_length=12),
        ),
    ]
