# Generated by Django 3.2.10 on 2023-12-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_alter_usermodel_avatar'),
        ('profile_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybybankmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.usermodel'),
        ),
        migrations.AlterField(
            model_name='paybymomomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.usermodel'),
        ),
        migrations.AlterField(
            model_name='paybypaypalmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.usermodel'),
        ),
    ]
