# Generated by Django 3.2.10 on 2023-12-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earn_money_app', '0003_auto_20231223_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkWeb1sStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=30)),
                ('list_user_retrieved', models.JSONField()),
            ],
        ),
    ]
