# Generated by Django 3.2.10 on 2023-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earn_money_app', '0004_linkweb1sstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkweb1sstorage',
            name='list_user_retrieved',
            field=models.JSONField(blank=True),
        ),
    ]
