# Generated by Django 3.2.10 on 2023-12-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earn_money_app', '0005_alter_linkweb1sstorage_list_user_retrieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkweb1sstorage',
            old_name='list_user_retrieved',
            new_name='list_access_token_user_retrieved',
        ),
    ]
